config/routes.rb
Rails.application.routes.draw do
  root "catalogues#index"
  resources :catalogues
  resources :reset_passwords, only: [:new, :create, :edit, :update]
end

app/models/admin.rb
class Admin < ApplicationRecord
  include UserBehaviour
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/attachment.rb
class Attachment < ApplicationRecord
  has_one_attached :main_image, dependent: :destroy
end

app/models/catalogue.rb
class Catalogue < ApplicationRecord
  has_many :education_materials
  has_one_attached :image, dependent: :destroy do |attachable|
    attachable.variant :thumb, resize_to_limit: [400, 400]
  end
  validates :title, :description, presence: true
  # validates :image, attached: true, content_type: [:jpg, :jpeg]
end

app/models/concerns/user_behaviour.rb
module UserBehaviour
  extend ActiveSupport::Concern

  included do
    attr_accessor :password

    validates :email, format: { with: URI::MailTo::EMAIL_REGEXP }
    validates :password, length: { minimum: 6 }

    after_validation :encrypt_password, if: -> { password.present? }

    private

    def encrypt_password
      data = Illustrations::WordMetamorphosis.new.call(password)

      self.encrypted_password = data[:encrypted_password]
      self.salt = data[:salt]
    end
  end
end

app/models/education_material.rb
class EducationMaterial < ApplicationRecord
  has_many :prices
  has_many :equipments
  belongs_to :catalogue
  has_many :messages, as: :messagable, dependent: :destroy

  validates :title, presence: true
end

app/models/equipment.rb
class Equipment < ApplicationRecord
  belongs_to :education_material
  validates :title, presence: true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :messagable, polymorphic: true
  validates :body, presence: true

  belongs_to :source_message, class_name: 'Message', foreign_key: :source_id, optional: true
  has_many :messages, class_name: 'Message', foreign_key: :source_id

  def source_message?
    source_id.blank?
  end

  def child_message?
    !source_message?
  end
end

app/models/price.rb
class Price < ApplicationRecord
  belongs_to :education_material
  validates :title, :amount, presence: true
  # TODO add price type (think out fancy name) column String type
end

app/models/purchase.rb
class Purchase < ApplicationRecord
  belongs_to :user
  belongs_to :education_material

  enum status: { pending: 'pending', succeeded: 'succeeded', canceled: 'canceled' }
  enum provider: { manual: 'manual', yookassa: 'yookassa' }

  validates :amount, presence: true, numericality: { greater_than: 0 }
  validates :title, :description, :currency, presence: true
  # TODO rename title to description
end

app/models/user.rb
class User < ApplicationRecord
  include UserBehaviour

  has_many :purchases
  has_many :messages, as: :messagable, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/catalogues_controller.rb
class CataloguesController < ApplicationController

  def new
    @catalogue = Catalogue.new
  end

  def create
    @catalogue = Catalogue.new(catalogue_params)
    if @catalogue.save
      redirect_to catalogue_path(@catalogue)
      flash[:notice] = "Create"
    else
      render :new
    end
  end

  def index
    @catalogues = Catalogue.all
  end

  def show
    @catalogue = Catalogue.find(params[:id])
  end

  def edit
    @catalogue = Catalogue.find(params[:id])
  end

  def update
    if @catalogue.update(catalogue_params)
      redirect_to catalogues_path
      flash[:notice] = "Успешно добавлен"
    else
      flash[:alert] = "Произошла ошибка"
      render :index
    end
  end

  private

  def catalogue_params
    params.require(:catalogue).permit(:image, :title, :description)
  end
end

app/controllers/reset_passwords_controller.rb
class ResetPasswordsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:email])

    if user
      user.create_token && user.password_sent_at

      if user.save
        # TODO send email to a user
        redirect_to root_path, notice: 'На ваш email отправлено письмо с инструкциями по восстановлению пароля.'
      else
        redirect_to reset_password_path, alert: 'Что-то пошло не так. Попробуйте еще раз.'
      end
    else
      redirect_to new_reset_password_path, alert: 'Пользователь с таким email не найден.'
    end
  end

  def edit
  end

  def update
    user = User.find_by(reset_password_token: params[:token])

    if user && user.reset_password_sent_at > 1.hour.ago
      if user.update(user_params)
        user.update(reset_password_token: nil, reset_password_sent_at: nil)
        redirect_to root_path, notice: 'Пароль успешно изменен.'
      else
        render :edit
      end
    else
      redirect_to new_reset_password_path, alert: 'Время действия ссылки истекло. Попробуйте восстановить пароль заново.'
    end
  end

  private

  def user_params
    params.require(:user).permit(:password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/catalogues/edit.html.erb
<%= link_to "Back", catalogues_path %>
<h1><%= @catalogue.title %></h1>

<%= form_with model: @catalogue, local: true do |form| %>
  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>
  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>
  <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image %>
  </div>
  <div class="actions">
    <%= form.submit "Upload" %>
  </div>
<% end %>

app/views/catalogues/index.html.erb
<p><%= link_to 'New', new_catalogue_path %></p>
<p>---------------------------</p>
<% @catalogues.each do | catalogue |%>
  <%= catalogue.title %>
  <%= link_to "Show", catalogue_path(catalogue) %>
  <% end %>

app/views/catalogues/new.html.erb
<% if @catalogue.errors.any? %>
  <% @catalogue.errors.full_messages.each do |message|%>\
    <h3><%= message %> </h3>
  <% end %>
<% end %>

</br>

<%= form_for @catalogue do |form| %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>
  <br>
  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
    <%# if @catalogue.errors[:description].any? %>
<!--      <p><%#= @catalogue.errors.full_messages_for(:description).join(', ') %></p>-->
    <%# end %>
  </div>
  <br>
  <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image %>
    <%# if @catalogue.errors[:image].any? %>
<!--      <p><%#= @catalogue.errors.full_messages_for(:image).join(', ') %></p>-->
    <%# end %>
  </div>
  <br>
  <div class="actions">
    <%= form.submit "Upload" %>
  </div>
<% end %>

app/views/catalogues/show.html.erb
<%= link_to "Back", catalogues_path %>
<%= link_to "Edit", edit_catalogue_path %>
<h1><%= @catalogue.title %></h1>
<h2><%= @catalogue.description %></h2>
<br>
<%= image_tag @catalogue.image.variant(:thumb) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MasterClass</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>